import DroppedDown from "@/components/DropDownList";
import { useUser } from "@/hooks/useUser";
import { ScrollView, Text, View } from "react-native";
import { HeaderText } from '../../components/HeaderText';
import { styles } from "../../styles";
export default function Index() {

  const quoteList:string[] = [
    "Keep going! Your future is worth the effort!", 
    "Keep moving and grooving, college awaits you.",
    "Don't give up! You'll thank yourself later.",
    "Take it a day at at a time. One step forward is all that is needed!",
    "Keep pushing—college dreams are worth every effort",
    "Every study session brings you closer to college",
    "Hard work today, bright college future tomorrow",
    "Stay focused—your college journey starts with determination",
    "Each step forward counts toward your college dream",
    "Believe in your ability to reach college success",
    "College doors open for those who persist",
    "You’re building your college future with every effort",
    "Keep going—your dedication will pay off soon",
    "Stay strong; your college dream is within reach",
    "Work hard now, shine later at college",
    "You’re capable of amazing things—college is one",
    "Your effort today shapes your college tomorrow",
    "Don’t quit—your college goal is getting closer",
    "Determination will carry you to college greatness",
    "College success begins with small, consistent steps",
    "Focus on progress, not perfection—college awaits",
    "Each challenge prepares you for college success",
    "You’re writing your college story with every choice",
    "Dream big, work hard, reach college heights",
    "Effort plus patience equals college achievement",
    "You’ve got what it takes to get there",
    "Keep believing—college is closer than you think",
    "Small wins add up to big college victories",
    "Stay committed; your college future is forming",
    "Hard work now brings college pride later",
    "You are destined for college greatness—keep going",
    "Push through—college rewards persistence and grit",
    "The journey to college starts with one step",
    "You’re stronger than any obstacle in your path",
    "Keep studying; your effort builds your college path",
    "You’ve come too far to give up now",
    "Every assignment moves you closer to college success",
    "Stay motivated; your goals are within sight",
    "Believe in progress—college dreams become reality",
    "Your determination is your greatest college tool",
    "Keep your vision clear; college is waiting",
    "Success follows effort—keep striving for college",
    "Each challenge conquered builds college readiness",
    "Stay positive; you’re preparing for something great",
    "Your hard work will open college doors",
    "Focus on your dream; college is possible",
"Consistency will take you all the way",
"You’re capable, strong, and college-bound",
"Every late night is one step closer",
"Your future self will thank you for this",
"Keep learning, keep growing, keep dreaming",
"The road may be tough, but you’re tougher",
"College is waiting for your brilliance to arrive",
"You’ve got this—keep chasing your college dream",
"Stay patient; growth takes time and effort",
"Keep your eyes on the college prize",
"Big dreams need steady, daily effort",
"Focus on what you can do today",
"Every small step matters on your college path",
"Stay curious—learning will take you far",
"Your effort today will shape your tomorrow",
"Hard work plants the seeds of success",
"Keep going even when it feels tough",
"College dreams grow through dedication and focus",
"Your mindset determines your college journey",
"You’re preparing yourself for endless opportunities",
"Perseverance always pays off in the end",
"Success is built one study session at a time",
"Stay hopeful; college dreams come true through effort",
"Keep showing up—that’s how success is made",
"Push a little harder every single day",
"Your dream deserves your best effort",
"You can achieve anything with consistency and focus",
"Stay humble, hungry, and hardworking",
"Your effort today earns pride tomorrow",
"Keep aiming high; college is worth it",
"Discipline will carry you when motivation fades",
"Each study hour builds your confidence and future",
"Stay inspired by your dreams of college",
"You’re capable of incredible academic success",
"Work now, celebrate your college victory later",
"Keep improving one day at a time",
"You’ve got the power to shape your path",
"Stay resilient through challenges and setbacks",
"Keep climbing—every step gets you closer",
"Your hard work defines your future success",
"Believe in yourself through every obstacle",
"Stay focused and your dream will bloom",
"Hard work creates the college future you imagine",
"Stay brave—great things await your effort",
"Persistence turns effort into achievement",
"Keep faith in your ability to succeed",
"You’re becoming stronger with every challenge",
"Stay consistent; progress takes patience",
"Push forward; every moment counts",
"You’re learning skills that will last forever",
"Hard work builds both knowledge and confidence",
"Stay determined even when it’s not easy",
"You can do this—college is calling",
"Keep your goals close and your effort closer",
"Your dedication sets you apart",
"Never stop believing in your potential",
"Stay motivated—college dreams take courage",
"Each success starts with steady effort",
"Keep faith in the process of growth",
"You’re creating a bright academic future",
"Keep chasing your college goals with passion",
"Your persistence will be your greatest reward",
"Small actions lead to big results",
"Work hard now, celebrate later at college",
"You’re building your own success story",
"Stay strong—college is closer every day",
"Believe you can, and you’re halfway there",
"Keep moving forward no matter how slow",
"Your dreams deserve every ounce of effort",
"Stay focused; distractions fade but success lasts",
"Every page studied brings you closer to success",
"Don’t give up—great things take time",
"Your effort inspires others around you",
"Stay positive—college is within your reach",
"You’re preparing for a lifetime of success",
"Every choice you make shapes your future",
"Keep grinding—progress takes patience",
"You’re capable of making your college dream real",
"Hard work opens doors that talent alone cannot",
"Stay committed; college success is worth it",
"Your focus will take you farther than fear",
"Keep rising after every challenge you face",
"You’re growing stronger through each obstacle",
"Stay consistent; results will come",
"Your time and effort will pay off soon",
"Keep believing in your goals",
"Each day brings new progress to celebrate",
"Hard work is the key to opportunity",
"Stay disciplined; success rewards consistency",
"You’re getting closer every single day",
"Keep pushing—you’re almost there",
"Your dream is worth the effort",
"Success begins with small daily habits",
"Stay passionate about your future",
"You’re proving your strength with every effort",
"Keep your head up and heart focused",
"You’ve got everything you need to succeed",
"Stay hopeful; your breakthrough is near",
"Hard work never goes unnoticed",
"Keep striving for your college goal",
"You’re stronger than self-doubt",
"Stay hungry for knowledge and growth",
"Every challenge makes you more prepared",
"Your dedication inspires your future self",
"Keep going; success takes time",
"Believe in effort more than luck",
"Stay steady; your dreams are valid",
"You’re almost where you want to be",
"Hard work transforms dreams into plans",
"Stay brave—your journey matters",
"Keep growing through challenges and wins",
"You’re capable of reaching incredible goals",
"Stay inspired by your own progress",
"Every moment of effort moves you forward",
"Your future will thank you for today",
"Keep choosing growth every single day",
"Believe you belong in college",
"Stay curious; learning is your superpower",
"Hard work always finds its reward",
"You’re creating your college success story",
"Keep aiming high and working hard",
"Your effort makes your dream possible",
"Stay patient and persistent",
"Every effort counts toward your dream",
"Keep studying—success is built, not given",
"You’re turning ambition into achievement",
"Stay focused on what truly matters",
"Hard work brings dreams to life",
"Keep going; progress takes courage",
"You’re closer than you think",
"Stay motivated by your vision",
"Every challenge helps you grow stronger",
"Your journey is worth every step",
"Keep learning and believing in yourself",
"You’ve got what it takes to succeed",
"Stay confident through every challenge",
"Hard work always leads somewhere good",
"Keep going; success is in your future",
"Your persistence will open new doors",
"Stay focused and fearless",
"Every dream starts with effort",
"Keep moving forward with hope",
"You’re writing your college success story",
"Stay proud of how far you’ve come",
"Hard work today, opportunity tomorrow",
"Keep believing—you belong in college",
"You’re unstoppable when you stay determined",
"Stay steady; progress is happening",
"Every step brings you closer to success",
"Keep working toward your college dream",
"You’re made for great things",
"Stay resilient; your time is coming",
"Hard work brings lasting rewards",
"Keep chasing the future you want",
"You’re building the life you dream of",
"Stay dedicated and unstoppable",
"Every bit of effort adds up",
"Keep striving; success is near",
"You’re proving dreams can come true",
]

  const rand: number = Math.floor(Math.random()*(180)) + 0
  const {logout, user} = useUser()


  return (
    <View style={styles.container}>
      <ScrollView showsVerticalScrollIndicator={false}>
        <View style={styles.container}>
        <HeaderText text="Welcome to" name="MinPlan." endText ="Jump right in."></HeaderText>
        <Text style={styles.quote}>{quoteList[rand]}</Text>
        <DroppedDown name="⏳ Weekly Goals  " note={true} plus={true}/>
        <DroppedDown name="❤️ Favorite Colleges  " note={false} plus={true}/>
        <Text onPress={logout} style={[styles.header, {paddingLeft:60, paddingRight:60}]}>Log out</Text>
        <Text>{user.email}</Text>

        {/* <Text style={[styles.quote, {paddingTop:65, paddingBottom:65, fontFamily:"Brico-Bold", fontWeight:600, backgroundColor:"#0D0D0D"}]}>        PlanningCO *2025       </Text> */}
      </View>
      </ScrollView>
    </View>
  )
}

//</ScrollView>  );